templateDir: ./sdk-resources/resources
packageName: plextv
packageVersion: 1.1.6
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
